image:
  name: docker/compose:1.23.1
  entrypoint: [""]

services:
  - name: docker:dind


before_script:
  - apk add --no-cache make bash curl git
# - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
  - build
  - deploy
  - test

build:
  stage: build
  script:
    - make build
#    - make push
  only:
    - stage
  tags:
    - ims-stage-deploy-runner

deploy:
  stage: deploy
  script:
#    - make pull
    - make deploy
  only:
    - stage
  tags:
    - ims-stage-deploy-runner

test-functional:
  stage: test
  variables:
    CI_COMMIT_REF_SLUG: test_functional_$CI_COMMIT_SHORT_SHA
  script:
    - make build
    - make test-functional-up
  after_script:
    - make test-functional-down
  only:
    - merge_requests
    - stage
  except:
    - schedules
  tags:
    - docker