services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  SsoBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Migrations,Tests,TelegramNotificationBundle.php}'

  SsoBundle\Controller\:
    resource: '../../Controller/'
    tags: [ 'controller.service_arguments' ]
