.PHONY: *

#Указываем конфигурацию для docker-compose
#Можно использовать наследование через символ ":", последний файл важнее
COMPOSE_FILE=./docker-compose.yml

#Общие команды
include ${PWD}/docker/deploy/common.mk